DEBUG

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -36,9 +36,15 @@ jobs:
           node-version: 18
           cache: 'npm'
       - name: Install dependencies
-        run: npm install
+        run: yarn install
       - name: Build
-        run: npm run build
+        run: yarn build
+      - name: Test
+        run: yarn coverage && |
+          if [[ ${{ steps.test-with-coverage.outcome }} == 'failure' ]]; then
+            echo "Tests failed"
+            exit 1
+          fi
       - name: Setup Pages
         uses: actions/configure-pages@v3
       - name: Upload artifact
